// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3133JngCPM8ceTcOuTvuSuEiy6vL7dzQ',
    appId: '1:1051720302845:web:f37996c91f31b3e5293e94',
    messagingSenderId: '1051720302845',
    projectId: 'arnhss',
    authDomain: 'arnhss.firebaseapp.com',
    storageBucket: 'arnhss.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB15lL2kFRkTEC9PeqYxe8_-MFARfxvkv4',
    appId: '1:1051720302845:android:d35de5dc7051a581293e94',
    messagingSenderId: '1051720302845',
    projectId: 'arnhss',
    storageBucket: 'arnhss.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKjo-5_8sc9gG0ETBvFBA6iU9397p3rhA',
    appId: '1:1051720302845:ios:c97d26c441e91ba1293e94',
    messagingSenderId: '1051720302845',
    projectId: 'arnhss',
    storageBucket: 'arnhss.appspot.com',
    iosClientId: '1051720302845-bdhfe4ek8jeskpe8shio4sv2u316bl46.apps.googleusercontent.com',
    iosBundleId: 'com.example.arnhssgvghhgfgh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKjo-5_8sc9gG0ETBvFBA6iU9397p3rhA',
    appId: '1:1051720302845:ios:36423bdf7140ae9a293e94',
    messagingSenderId: '1051720302845',
    projectId: 'arnhss',
    storageBucket: 'arnhss.appspot.com',
    iosClientId: '1051720302845-f0nrqhheqj6u0iedppmv0lscc2v7ou1j.apps.googleusercontent.com',
    iosBundleId: 'com.example.arnhss',
  );
}
