// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD40xF0ybbBczDcEpkRPdu9UzkX_l2bIFM',
    appId: '1:724320524720:android:48f02a29ef2ceb9e91de75',
    messagingSenderId: '724320524720',
    projectId: 'arnhss-backend',
    databaseURL: 'https://arnhss-backend-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'arnhss-backend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbJHfY6VL1KSjB260vVGCenlzKm7K5Y0c',
    appId: '1:724320524720:ios:665922f23883908491de75',
    messagingSenderId: '724320524720',
    projectId: 'arnhss-backend',
    databaseURL: 'https://arnhss-backend-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'arnhss-backend.appspot.com',
    iosClientId: '724320524720-bb17fqrj0m06rdl4id6ioqg4gf84m997.apps.googleusercontent.com',
    iosBundleId: 'sampl.a',
  );
}
