// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQXRuDu7qmC0Sy_mQqtw6RnjjPYeW1gIo',
    appId: '1:724320524720:web:4a028ae418b2c0e191de75',
    messagingSenderId: '724320524720',
    projectId: 'arnhss-backend',
    authDomain: 'arnhss-backend.firebaseapp.com',
    storageBucket: 'arnhss-backend.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD40xF0ybbBczDcEpkRPdu9UzkX_l2bIFM',
    appId: '1:724320524720:android:48f02a29ef2ceb9e91de75',
    messagingSenderId: '724320524720',
    projectId: 'arnhss-backend',
    storageBucket: 'arnhss-backend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbJHfY6VL1KSjB260vVGCenlzKm7K5Y0c',
    appId: '1:724320524720:ios:030562d9b4c936d491de75',
    messagingSenderId: '724320524720',
    projectId: 'arnhss-backend',
    storageBucket: 'arnhss-backend.appspot.com',
    iosClientId: '724320524720-9nfsp28ovgacouh8bcem7a2drt1hd1q0.apps.googleusercontent.com',
    iosBundleId: 'com.example.arnhssgvghhgfgh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbJHfY6VL1KSjB260vVGCenlzKm7K5Y0c',
    appId: '1:724320524720:ios:7f7d06287dcc719f91de75',
    messagingSenderId: '724320524720',
    projectId: 'arnhss-backend',
    storageBucket: 'arnhss-backend.appspot.com',
    iosClientId: '724320524720-mopifmdjostbgb4v3rds5l3ef8sk7gg0.apps.googleusercontent.com',
    iosBundleId: 'com.example.arnhss',
  );
}
